#!/bin/bash

question_type=password
dialog_title=
dialog_text=
backend=any

for arg in "$@"
do
   case "$arg" in
      --password)
         question_type=password
         ;;
      --question)
         question_type=yesno
         ;;
      --title=*)
         dialog_title=${arg#--title=}
         ;;
      --text=*)
         dialog_text=${arg#--text=}
         ;;
      --backend=*)
         backend=${arg#--backend=}
         ;;
   esac
done

if [ "$backend" = "pinentry" ] || { [ "$backend" = "any" ] && which pinentry &> /dev/null ;}
then
   case "$question_type" in
      password)
         echo -e "SETTITLE $dialog_title\nSETDESC Please enter password\nSETPROMPT Password:\nGETPIN\n" | pinentry | grep "^D " | cut -b3-
         ;;
      yesno)
         if echo -e "SETTITLE $dialog_title\nSETDESC $dialog_text\nSETOK Yes\nSETCANCEL No\nCONFIRM\n" | pinentry | grep -q "^ERR "
         then
            exit 1
         else
            exit 0
         fi
         ;;
   esac
elif [ "$backend" = "zenity" ] || { [ "$backend" = "any" ] && [ "$DISPLAY" ] && which zenity &> /dev/null ;}
then
   case "$question_type" in
      password)
         zenity --no-markup --password --title="$dialog_title" 
         ;;
      yesno)
         zenity --no-markup --question --title="$dialog_title" --text="$dialog_text"
         ;;
   esac
else
   # CLI pure Bash backend
   case "$question_type" in
      password)
         echo "$dialog_title" > /dev/tty
         echo "----------------------------------------" > /dev/tty
         echo -n "Password: " > /dev/tty
         read -s password
         echo "$password"
         ;;
      yesno)
         echo "$dialog_title" > /dev/tty
         echo "----------------------------------------" > /dev/tty
         while true
         do
            echo "$dialog_text (y/n)" > /dev/tty
            read 
            if [ "${REPLY:0:1}" = "y" -o "${REPLY:0:1}" = "Y" ]
            then
               exit 0
            elif [ "${REPLY:0:1}" = "n" -o "${REPLY:0:1}" = "N" ]
            then
               exit 1
            fi
         done
         ;;
   esac
fi
